function clamp( v, min = -1, max = 1 ) {

	return Math.max( min, Math.min( max, v ) )

}

function clamp01( v ) {

	return Math.max( 0, Math.min( 1, v ) )

}

/**
 * Affective forecasting: emotion generated by what the AI EXPECTS to happen,
 * not only by what already happened (Wilson, T. D., & Gilbert, D. T. (2003),
 * "Affective forecasting", Advances in Experimental Social Psychology, 35,
 * 345-411). Reuses BayesianExpectation's real posterior (already a genuine
 * P(positive outcome) estimate per user) as the forecast's valence sign and
 * confidence, converts it into a concrete expected-valence/arousal pair, and
 * — the real mechanic — computes the forecast ERROR once the actual outcome
 * is known, which is exactly the same real signal DopaminergicEngine's RPE
 * already consumes, so a wrong anticipation genuinely corrects future
 * anticipation the way TD learning does, not just the reward-prediction
 * system alone.
 */
export class AnticipatoryAffect {

	/** BayesianExpectation posterior -> a concrete forecast the AI can feel BEFORE the turn's real outcome is known. */
	forecast( bayesianExpectation, userId ) {

		const p          = bayesianExpectation.getExpectation( userId )
		const anxiety     = bayesianExpectation.getAnxiety( userId )
		const expectedValence = clamp( ( p - 0.5 ) * 2 )
		const expectedArousal = clamp01( anxiety ) // anticipating a bad outcome is itself arousing

		// Confidence: how far the posterior sits from an uninformative 0.5 —
		// a forecast near neutral is a weak forecast regardless of arousal.
		const confidence = clamp01( Math.abs( p - 0.5 ) * 2 )

		return { expectedValence, expectedArousal, confidence, posterior: p }

	}

	/** Real forecast error — the gap between what was anticipated and what actually happened, signed (positive = better than feared/hoped). */
	getForecastError( forecastResult, actualValence ) {

		return clamp( actualValence - forecastResult.expectedValence )

	}

	/** Feeds the forecast error into DopaminergicEngine as a direct expectation nudge — a wrong anticipation updates the NEXT forecast, real backward correction. */
	applyCorrection( dopaminergicEngine, context, forecastError, weight = 0.25 ) {

		dopaminergicEngine.updateExpectationFromBelief( context, forecastError, weight )

	}

}
